import Head from 'next/head';
import Image from 'next/image';
import Carousel from '../components/Carousel/Carousel';
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';

import Story from '../components/Story/Story';

import styles from '../styles/Home.module.scss';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Header />
				<Story />
				<Carousel />
			</main>

			<footer>
				<Footer />
			</footer>
		</div>
	);
}
